server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:sqlserver://localhost:1433;databaseName=activity_hub;encrypt=false}
    driverClassName: "com.microsoft.sqlserver.jdbc.SQLServerDriver"
    password: "Admin@123"
    username: "sa"
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        order_inserts: true
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 1800 # 30 minutes in seconds (access token)
  refreshable-duration: 86400 # 1 day in seconds (refresh token)
  refreshable-duration-long: 1296000 # 15 days in seconds (refresh token for remember me)

